"""empty message

Revision ID: 5aadc0fa4530
Revises: 857a7a824089
Create Date: 2019-10-28 09:31:11.891693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aadc0fa4530'
down_revision = '857a7a824089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectcode', sa.String(length=50), nullable=False),
    sa.Column('projectname', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('projectlocation', sa.String(length=100), nullable=False),
    sa.Column('project_image', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectcode'),
    sa.UniqueConstraint('projectname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
