"""empty message

Revision ID: 857a7a824089
Revises: 
Create Date: 2019-05-06 21:00:06.850690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '857a7a824089'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('product', sa.Column('prod_image', sa.String(length=20), nullable=True))
    op.add_column('product', sa.Column('prodcode', sa.String(length=50), unique=True, nullable=False))
    op.add_column('product', sa.Column('qty_onhand', sa.Float(), nullable=False))
    op.add_column('product', sa.Column('re_order', sa.Float(), nullable=False))
    op.add_column('product', sa.Column('uom', sa.String(length=20), nullable=False))
    op.alter_column('product', 'location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_product_prodcode'), 'product', ['prodcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_prodcode'), table_name='product')
    op.alter_column('product', 'location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('product', 'uom')
    op.drop_column('product', 're_order')
    op.drop_column('product', 'qty_onhand')
    op.drop_column('product', 'prodcode')
    op.drop_column('product', 'prod_image')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
